# SPDX-FileCopyrightText: Copyright 2023 The OpenVEX Authors
# SPDX-License-Identifier: Apache-2.0
---
name: Release

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to write releases

    steps:
      - name: Publish Release
        uses: kubernetes-sigs/release-actions/publish-release@b5b8280a60e6e20607f77068011269b982c60971 # v0.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
